blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/milikadelic/SmartTube/discussions
    about: For questions, ideas, or general discussion please use GitHub Discussions.
