import Testing
import Foundation
@testable import SmartTubeIOSCore

// MARK: - CaptionsManager unit tests
//
// Tests verify the four key behaviours from task #63:
//   1. updateCaptionCue finds the active cue for a given time
//   2. updateCaptionCue returns nil when no cue spans the time
//   3. reset() clears all caption state and cancels any running fetch
//   4. selectCaption(nil) clears selection immediately

@Suite("CaptionsManager")
struct CaptionsManagerTests {

    // MARK: - 1. updateCaptionCue finds active cue

    @Test("updateCaptionCue returns cue whose window contains the given time")
    @MainActor func updateCaptionCueFindsMatch() async {
        let manager = CaptionsManager()
        manager.captionCues = [
            CaptionCue(startTime: 0.0, endTime: 2.0, text: "Hello"),
            CaptionCue(startTime: 3.0, endTime: 6.0, text: "World"),
            CaptionCue(startTime: 7.0, endTime: 10.0, text: "Goodbye"),
        ]
        manager.updateCaptionCue(for: 4.5)
        #expect(manager.currentCaptionCue?.text == "World")
    }

    // MARK: - 2. No cue outside windows

    @Test("updateCaptionCue returns nil when time is between cues")
    @MainActor func updateCaptionCueReturnsNilBetweenCues() async {
        let manager = CaptionsManager()
        manager.captionCues = [
            CaptionCue(startTime: 0.0, endTime: 2.0, text: "First"),
            CaptionCue(startTime: 5.0, endTime: 8.0, text: "Second"),
        ]
        manager.updateCaptionCue(for: 3.0)
        #expect(manager.currentCaptionCue == nil)
    }

    // MARK: - 3. reset() clears all state

    @Test("reset() clears availableCaptions, selectedCaption, cues, and cancels task")
    @MainActor func resetClearsAllState() async {
        let manager = CaptionsManager()
        let track = CaptionTrack(id: "en", baseURL: URL(string: "https://example.com")!,
                                  name: "English", languageCode: "en", isAutoGenerated: false)
        manager.availableCaptions = [track]
        manager.selectedCaption = track
        manager.currentCaptionCue = CaptionCue(startTime: 0, endTime: 1, text: "hi")
        manager.captionCues = [CaptionCue(startTime: 0, endTime: 1, text: "hi")]
        manager.captionFetchTask = Task { try? await Task.sleep(nanoseconds: 1_000_000_000) }

        manager.reset()

        #expect(manager.availableCaptions.isEmpty)
        #expect(manager.selectedCaption == nil)
        #expect(manager.currentCaptionCue == nil)
        #expect(manager.captionCues.isEmpty)
        #expect(manager.captionFetchTask == nil)
    }

    // MARK: - 4. selectCaption(nil) clears selection

    @Test("selectCaption(nil) clears selection and cues without starting a fetch")
    @MainActor func selectCaptionNilClearsSelection() async {
        let manager = CaptionsManager()
        let track = CaptionTrack(id: "fr", baseURL: URL(string: "https://example.com")!,
                                  name: "French", languageCode: "fr", isAutoGenerated: false)
        manager.selectedCaption = track
        manager.captionCues = [CaptionCue(startTime: 0, endTime: 2, text: "bonjour")]

        manager.selectCaption(nil)

        #expect(manager.selectedCaption == nil)
        #expect(manager.captionCues.isEmpty)
        #expect(manager.captionFetchTask == nil)
    }

    // MARK: - 5. Empty cues returns nil

    @Test("updateCaptionCue returns nil when captionCues is empty")
    @MainActor func updateCaptionCueEmptyCues() async {
        let manager = CaptionsManager()
        manager.updateCaptionCue(for: 5.0)
        #expect(manager.currentCaptionCue == nil)
    }
}
